# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
