# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificaciones', '0002_auto_20160728_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='creador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
