# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_alerta_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
