# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-02 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0005_auto_20160728_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta_miembro',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
