# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 12:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('nombre_pdf', models.CharField(max_length=250)),
                ('visible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrador.Empresa')),
            ],
            options={
                'verbose_name_plural': 'Reportes',
                'verbose_name': 'Reporte',
            },
        ),
        migrations.CreateModel(
            name='Reporte_Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('codigo', models.CharField(blank=True, max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(max_length=7)),
                ('icono', models.CharField(max_length=250)),
                ('visible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now=True)),
                ('empresas', models.ManyToManyField(blank=True, to='administrador.Empresa')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Reportes',
                'verbose_name': 'Tipo de Reporte',
            },
        ),
        migrations.AddField(
            model_name='reporte',
            name='reporte_tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporteria.Reporte_Tipo'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
