# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrador', '0011_remove_empresa_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte_Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('codigo', models.CharField(blank=True, max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now=True)),
                ('empresas', models.ManyToManyField(to='administrador.Empresa')),
            ],
        ),
    ]
