# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteria', '0002_reporte'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporte',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterModelOptions(
            name='reporte_tipo',
            options={'verbose_name': 'Tipo de Reporte', 'verbose_name_plural': 'Tipos de Reportes'},
        ),
        migrations.AddField(
            model_name='reporte',
            name='nombre_pdf',
            field=models.CharField(default='asd', max_length=250),
            preserve_default=False,
        ),
    ]
