# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrador', '0011_remove_empresa_moneda'),
        ('reporteria', '0003_auto_20160808_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrador.Empresa'),
            preserve_default=False,
        ),
    ]
