# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteria', '0004_reporte_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte_tipo',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporte_tipo',
            name='icono',
            field=models.CharField(default='fa fa-trash', max_length=250),
            preserve_default=False,
        ),
    ]
