# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporteria', '0005_auto_20160808_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='nombre_pdf',
        ),
    ]
