# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteria', '0006_remove_reporte_nombre_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_tipo',
            name='empresas',
            field=models.ManyToManyField(blank=True, to='administrador.Empresa'),
        ),
    ]
