# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporteria', '0007_auto_20160809_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='nombre_pdf',
            field=models.CharField(default='reporte', max_length=250),
            preserve_default=False,
        ),
    ]
