# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('visible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Comunas',
                'verbose_name': 'Comuna',
            },
        ),
        migrations.CreateModel(
            name='Estado_Civil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Estados Civiles',
                'verbose_name': 'Estado Civil',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('simbolo', models.CharField(max_length=250)),
                ('abrev', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Monedas',
                'verbose_name': 'Moneda',
            },
        ),
        migrations.CreateModel(
            name='Moneda_Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilidades.Moneda')),
            ],
            options={
                'verbose_name_plural': 'Historial de Monedas',
                'verbose_name': 'Historial de Moneda',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('visible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'verbose_name': 'Provincia',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('ordinal', models.CharField(max_length=250)),
                ('visible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Regiones',
                'verbose_name': 'Región',
            },
        ),
        migrations.CreateModel(
            name='Tarifa_Electricidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=250)),
                ('valor', models.FloatField()),
                ('descripcion', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tarifas de Electricidad',
                'verbose_name': 'Tarifa de Electricidad',
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilidades.Region'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilidades.Provincia'),
        ),
    ]
