# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-10 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0002_estado_civil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa_Electricidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=250)),
                ('valor', models.FloatField()),
                ('descripcion', models.TextField(blank=True)),
                ('visible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
