# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0004_moneda_moneda_historial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='estado_civil',
            options={'verbose_name': 'Estado Civil', 'verbose_name_plural': 'Estados Civiles'},
        ),
        migrations.AlterModelOptions(
            name='moneda',
            options={'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterModelOptions(
            name='moneda_historial',
            options={'verbose_name': 'Historial de Moneda', 'verbose_name_plural': 'Historial de Monedas'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Región', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='tarifa_electricidad',
            options={'verbose_name': 'Tarifa de Electricidad', 'verbose_name_plural': 'Tarifas de Electricidad'},
        ),
    ]
